INSERT INTO "public"."customers" ("id", "name", "phone", "email", "address", "created_at", "cpf", "rg", "profissao", "nacionalidade", "estado_civil", "endereco_completo", "cidade", "medico_responsavel", "tipo_cirurgia", "data_cirurgia", "indicacao", "situacao_cadastral", "comprovante_residencia_url", "documento_identidade_url") VALUES ('21', 'Paula Urca', '21 99853-9400', '', 'Alameda dos Instrutores 1, bloco A Urca', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('36', 'Alessandra Taquara ', '21 98792-9287', '', 'Rua Marapendi 366, bl.2 /508
Taquara 
Entrega antecipada dia 21/07.', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('40', 'Renata Itaipuaçu ', '21 98849-3598', '', 'Rua Manuel Figueiredo lote 34, quadra 527, Jd. Atlântico Leste Itaipuaçu ', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('41', 'Cristina Ilha do Governador ', '21 98176-5430', '', 'Rua Juraci Camargo 600 apto 106.
Ilha do Governador.
', null, '372.426.797-53', '03428378-8', 'Contadora', 'Brasileira', 'Viúva ', 'Rua Juraci Camargo n. 600 apto 106, Ilha do Governador', 'Rio de Janeiro/ RJ ', 'Dr. Marcelo Moreira ', '', '2025-07-25', 'Satya', 'ativo', null, null), ('42', 'Heliana Tijuca', '21 98665-3286', '', 'Rua Afonso Pena 141 ap 802
Tijuca', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('43', 'Paula Mage', '21986674352', '', 'Rua D, n225 loteamento dos meninos, Piedade,  Mage.', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('44', 'Valeria Itaipuaçu ', '21976623074', '', 'Rua Gov Leonel Brizola, lote 33, quadra 369, casa 1. Jardim Atlântico Leste, Itaipuaçu,  Marica. RJ.', null, '03224626739', '09.925.807-1', 'Empresaria', 'Brasileira', 'Casada', 'Rua Gov Leonel Brizola, lt33, quadra 369, Casa 1, Jardim Atlântico Leste, Itaipuaçu, ', 'Marica, RJ', '', '', '2025-07-29', '', 'ativo', null, null), ('46', 'Antônio Anderson Méier ', '21 97900-0349', '', 'Rua Gustavo Gama 185
Méier', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('49', 'Carolina São Francisco ', '21 99130-7565', '', 'Av. Quintino Bocaiúva, 151, apt.413- São Francisco.', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('50', 'Carolina São Francisco ', '21 99130-7565', '', 'Av. Quintino Bocaiúva, 151, apt.413- São Francisco.', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('51', 'Carmem Lúcia Icaraí ', '22 99893-5917', '', 'Rua Cinco de Julho 318/1101. Jardim Icaraí Niterói-RJ', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('52', 'Fabiane Centro Niterói ', '21 99305-6479', '', 'Rua Belisario Augusto, 30 Bl.1 Apt. 802
Niterói-RJ', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('53', 'Tatiane Centro Niterói ', '21 99870-8063', '', 'Rua Marquês de Paraná n.348, bloco 3, apt.405 Centro Niterói RJ', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('54', 'Tatiane Centro Niterói ', '21 99870-8063', '', 'Rua Marquês de Paraná n.348, bloco 3, apt.405 Centro Niterói RJ', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('55', 'Gleyci Caxias', '21 98035-0532', '', 'Condomínio Garden Village Xerem Caxias-RJ ', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('56', 'Nice Rafael Niterói-RJ ', '21 98606-2503', '', 'Av. Jornalista Alberto Francisco Torres 185 1303 b, icarai Niterói ', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('57', 'Fatima Penha', '21 99936-7190', '', 'Rua Cintra n.113
Penha/ Rio de Janeiro-RJ ', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('58', 'Lohany Riviera del Sol ', '21 98823-0626', '', 'Condomínio Riviera del Sol Recreio dos Bandeirantes.', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('59', 'Raissa Icaraí Dra. Gisela', '21 98577-5067', '', 'Rua Pereira da Silva 137, apto.2404 Icaraí Niterói-RJ ', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('60', 'Graziella Caxias', '21 96494-3898', '', 'Rua Ana Neri n.102, apto 505/2
Duque de Caxias-RJ ', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('62', 'Michelle Laranjeiras Dr. Marcelo Moreira ', '21 98172-2878', '', 'Rua Almirante Benjamim Sodré n.40/ apt.503 Laranjeiras', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('63', 'Luisy Av. Central', '21 98061-3730', '', 'Rua Arthur Maia lote 23 quadra 23
Niterói/Maravista
', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('64', 'Vanda Centro Niterói ', '35 9183-8926', '', 'Rua São José n.42 loja 
Centro Niterói ', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('65', 'Thamyris Pendotiba ', '21 97715-2475', '', 'Estrada da Paciência 1235
Condomínio Aldeias de Pendotiba, bloco 3, apto 504', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('66', 'Andrea Ubá IV ', '21 99851-2002', '', 'Estrada Francisco da Cruz Nunes 8.100 casa 203 - Condomínio Ubá IV - Piratininga 
CEP - 24.350-310 Niterói
', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('67', 'Thayane Recreio Cond.Art Life', '21 99829-7944', '', 'Estrada Vereador Alceu de Carvalho 555 - Condomínio Art Life - Recreio (casa i 3a) ', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('68', 'Hadassa Praia de Botafogo ', '11 98175-2321', '', 'Praia de Botafogo, 142 apto 302', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('69', 'Thati Engenho de Dentro Dr. Marcelo', '21 96953-8402', '', 'Rua Eulina Ribeiro 310, bl.1/407 Engenho de Dentro ', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('70', 'Claudia Maria Feijó Sampaio', '21 98288-2966', '', 'Rua Miguel Couto, 275/1401, Icaraí , Niterói.', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('71', 'Laís Icaraí Dra. Gisela ', '21 99855-4666', '', 'Rua Dr. Tavares de Macedo,  20, apt 2201 bloco 2, Icaraí / Niterói. 
', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('72', 'Patricia Ilha', '21 99264-0858', '', 'Rua Adolfo Porto, n. 245 ap 201, Moneró Ilha do Governador / Rio de Janeiro
', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null), ('73', 'Carina Icaraí ', '21 99972-8803', '', 'Rua Domingues de Sá n.461 apto 607 Niterói.', null, null, null, null, null, null, null, null, null, null, null, null, 'ativo', null, null);